# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ee726476e9933f496fe83cd23973f98c66fe3916fe44845c1823abb2e7fe8c3ce09eba0880504cfb250ec1f7d82bc25fee8b7ec3d291339d08132b1d368e8ec

test:
  secret_key_base: 483b7f3ca7027e0d4d8704da3476344417435c0d4a3a42dc591ccb596e8bc4031f02a2d57ebb02d320a7e010a788ad57e97b7fb8dd127f51fbcb8b56a262b1bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
